# Generated by Django 4.1.6 on 2023-02-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_student_pincode_alter_student_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contactno',
            field=models.IntegerField(),
        ),
    ]
