# Generated by Django 4.1.6 on 2023-02-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_student_contactno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pincode',
            field=models.CharField(max_length=7),
        ),
    ]
